### ISSUE TITLE
🔧 [기능요청][서버이전] GCP 만료에 따른 AWS 서버 인스턴스 초기설정

### ISSUE THREAD

**Issue by Chuseok22** [Team-DailySnap/DailySnap-BE#88]
📝 현재 문제점
---

- GCP 무료이용 기간이 종료됨에 따라 AWS로 서버를 이전합시다

🛠️ 해결 방안 / 제안 기능
---

# AWS 인스턴스 설정 (@HyerimH )
## 인스턴스 생성
- [ ] 프리티어 범위에 벗어나지 않게 ubuntu 인스턴스를 생성 (스토리지는 30GB 최대로 설정해주세요)
- [ ] 처음 생성하면 pem키를 사용하여 서버 접속 가능 -> pem키로 접속하는 방식 그대로 유지한 채 비밀번호를 통해서 ssh 접속 가능하도록 설정해주세요
- [ ] ssh 기본 포트는 22번을 사용합니다 -> ssh 포트 2022 로 변경해주세요
- [ ] 기본 사용자는 `ubuntu`입니다 -> 기본 사용자는 유지한 채 새로운 admin 사용자 만들어주세요 (username 자유)
- [ ] 기본 admin사용자는 사용하지 않는 것이 보안 측면에서 유리합니다 -> 새로운 사용자 생성 후 기본 사용자 `ubuntu`는 `rootLogin = false`를 통해 비활성화
- [ ] 서버 ip를 고정하고, 방화벽 설정을 진행합니다 -> `ssh 2022`, `5432 postgresql`, `27017 mongoDB`, `redis 6379`, `http 80`, `https 443`, `rds 3389` 등등 필요한 포트 모두 열어주세요
- [ ] aws 프리티어 인스턴스는 기본적으로 1GB램을 지원합니다 (짠돌이들..) 1GB램으로 서버 올리면 docker 컨테이너 하나 올리자마자 바로 펑~ 터지니까 스왑메모리 설정해주세요 스왑메모리는 6GB설정합시다
- [ ] 서버 docker 설치
- [ ] docker 설치 후 `portainer` 컨테이너 올리기
- [ ] 모든 docker 컨테이너는 `docker-compose.yml`파일을 생성하여 올립시다 -> 추후 유지보수 용이성

## Docker 경로
- 각 DB docker 이미지 버전은 원하는대로 변경해도 됩니다 
- 최신 버전을 사용하고 싶으면 `latest`태그 사용하시구
### PostgreSQL
- 볼륨: docker/postgres
- yml경로: docker/docker-compose/postgres/docker-compose.yml

```
version: "3.8"

services:
  postgres:
    image: postgres:14
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER={username}
      - POSTGRES_PASSWORD={password}
      - POSTGRES_DB=postgres_db
    ports:
      - "5432:5432"
    volumes:
      - /volume1/docker/postgres:/var/lib/postgresql/data {여기 수정 잘하세요}
```

### MongoDB
- 볼륨: docker/mongo
- yml경로: docker/docker-compose/mongo/docker-compose.yml

```
version: '3.8'

services:
  mongodb:
    image: mongo:4.4  # 4.4 mongo 이미지 사용 {synology nas 에서는 5버전 미만만 지원해서 4.4를 사용했어요 aws인스턴스에서는 알아서 사용하고 싶은거 사용하면 됩니다}
    container_name: mongodb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME={username}
      - MONGO_INITDB_ROOT_PASSWORD={password}
    ports:
      - "27017:27017"  # 호스트의 27017 포트를 컨테이너의 27017 포트로 매핑
    volumes:
      - /volume1/docker/mongodb:/data/db  # /volume1/docker/mongo 매핑 {볼륨 매핑 수정 필요!!!}
```

### Redis
- 볼륨: docker/redis
- yml경로: docker/docker-compose/redis/docker-compose.yml

```
version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"  # 호스트의 6379 포트를 컨테이너의 6379 포트로 매핑
    volumes:
      - /volume1/docker/redis:/data  # Redis 데이터 디렉토리 매핑
    command: redis-server --appendonly yes  # AOF(Append-Only File) 활성화로 데이터 영속성 보장
```

#### docker 폴더 내부 docker-compose, postgres, mongo, redis
- 해당 `postgres`, `mongo`, `redis`는 볼륨!!! 입니다
![Image](https://github.com/user-attachments/assets/f4813754-6b24-47d2-b528-3a6e843e052a)

#### docker/docker-compose 내부 postgres, mongo, redis
- 해당 `postgres`, `mongo`, `redis`내부에는 `docker-compose.yml`파일이 위치하면 됩니다
![Image](https://github.com/user-attachments/assets/6a4dca3e-555b-401a-87d0-679989a5246d)

### 컨테이너
1. `portainer` 9000번 포트
2. `postgresql` 5432번 포트
3. `mongodb` 27017번 포트
4. `redis` 3389번 포트
요렇게 4개 올려놓으면 됩니다 당연히 연결 확인까지 끝내야돼요 이후 cicd과정에서 db연결때문에 문제 생기지 않도록 부탁드립니다

🙋‍♂️ 담당자
---
- 백엔드: @HyerimH @nayoung04 
- 프론트엔드: 이름
- 디자인: 이름
